version: '3.9'

services:
  backend:
    build:               # set that the will be build from a Dockerfile
      context: ./backend      # the path to the Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"       # math the PC port with the container port
    volumes:
      - ./app:/app      # define the folder mapping inside the container
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:        # database connection settings
      - DB_HOST=db      
      - DB_NAME=devdb      
      - DB_USER=devuser     
      - DB_PASS=changeme    
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine3.20
    volumes:    # se crea un volumen para guardar y cargar la info en la base de datos
      - dev-db-data:/var/lib/postgresql/data
    environment:    # se define las variables para la base de datos
      - POSTGRES_DB=devdb       # nombre de la base de datos
      - POSTGRES_USER=devuser       # usuario
      - POSTGRES_PASSWORD=changeme   # password

volumes:
  dev-db-data:
  dev-static-data: