# Generated by Django 5.1.4 on 2025-01-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
