# Generated by Django 5.1.4 on 2025-01-13 20:47

import authentication.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, validators=[authentication.validators.validate_us_phone_number]),
        ),
    ]
