# Generated by Django 5.1.4 on 2025-01-14 14:58

import authentication.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid US phone number.', max_length=128, region='US', validators=[authentication.validators.validate_us_phone_number]),
        ),
    ]
