# Generated by Django 5.1.4 on 2025-01-24 15:55

import authentication.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=400)),
                ('in_use', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=6)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('building', 'Edificio'), ('chalet', 'Chalet'), ('land', 'Terreno')], max_length=20)),
                ('address', models.TextField(max_length=255)),
                ('county', models.TextField(max_length=50)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('for_sale_or_rent', models.BooleanField()),
                ('price', models.IntegerField(max_length=9)),
                ('beds', models.IntegerField(blank=True)),
                ('full_baths', models.IntegerField(blank=True)),
                ('half_baths', models.IntegerField(blank=True)),
                ('square_ft', models.IntegerField(blank=True)),
                ('water_front', models.IntegerField(blank=True)),
                ('built', models.IntegerField(blank=True, max_length=4)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('owner', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid US phone number +1XXXXXXXXXX.', max_length=128, region='US', validators=[authentication.validators.validate_us_phone_number])),
            ],
        ),
    ]
