# Generated by Django 5.1.4 on 2025-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comments_realestateproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='built',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
