# Generated by Django 5.1.4 on 2025-01-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_realestateproperty_built_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateproperty',
            name='for_sale_or_rent',
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='county',
            field=models.CharField(choices=[('for_sale', 'En venta'), ('for_rent', 'En renta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='lon',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
