# Generated by Django 5.1.4 on 2025-01-24 18:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_realestateproperty_for_rent_or_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='county',
            field=models.CharField(choices=[('Broward', 'Broward'), ('Charlotte', 'Charlotte'), ('Collier', 'Collier'), ('Glades', 'Glades'), ('Hendry', 'Hendry'), ('Highlands', 'Highlands'), ('Lee', 'Lee'), ('Martin', 'Martin'), ('Miami Dade', 'Miami Dade'), ('Monroe', 'Monroe'), ('Okeechobee', 'Okeechobee'), ('Palm Beach', 'Palm Beach'), ('Saint Lucie', 'Saint Lucie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='zip_code',
            field=models.IntegerField(validators=[core.validators.validate_zip_code]),
        ),
    ]
