# Generated by Django 5.1.4 on 2025-01-25 19:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_realestateproperty_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='built',
            field=models.IntegerField(blank=True, validators=[core.validators.validate_built]),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='property_type',
            field=models.CharField(choices=[('Single Family', 'Single Family'), ('Condo/Co-Op/Villa/Townhouse', 'Condo'), ('Multi-Family Income', 'Multi Family'), ('Residential Land/Boat Docks', 'Residential Land'), ('Land-Commercial/Business/Agricultural/Industrial', 'Bussiness'), ('Residential Rental', 'Residential Rental'), ('Commercial/Industrial', 'Commercial'), ('Business Brokerage', 'Bussiness Brokerage')], max_length=100),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='water_front',
            field=models.BooleanField(default=False),
        ),
    ]
