# Generated by Django 5.1.5 on 2025-01-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_realestateproperty_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='realestateproperty',
            options={'ordering': ['-id'], 'verbose_name': 'Real Estate Property', 'verbose_name_plural': 'Real Estate Properties'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
