# Generated by Django 5.1.6 on 2025-02-09 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.realestateproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Property',
                'verbose_name_plural': 'Favorite Properties',
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_properties',
            field=models.ManyToManyField(related_name='favorited_by', through='core.FavoriteProperty', to='core.realestateproperty'),
        ),
    ]
