# Generated by Django 5.1.6 on 2025-02-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_favoriteproperty_user_favorite_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproperty',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='price_decrease',
            field=models.BooleanField(default=False),
        ),
    ]
