# Generated by Django 5.1.6 on 2025-03-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_realestateproperty_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
