# Generated by Django 5.1.6 on 2025-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_comments_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='beds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='full_baths',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='half_baths',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='square_ft',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
