# Generated by Django 5.1.6 on 2025-04-22 16:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_realestateproperty_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='built',
            field=models.IntegerField(blank=True, default=1950, validators=[core.validators.validate_built]),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
