# Generated by Django 5.1.8 on 2025-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_realestateproperty_built_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproperty',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
